# Generated by Django 2.1.7 on 2019-03-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookLoan', '0002_auto_20190324_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='status',
            field=models.CharField(choices=[('P', 'Pending Approval'), ('A', 'Approved'), ('O', 'Open'), ('C', 'Closed')], default='P', max_length=1),
        ),
    ]
