# Generated by Django 2.1.7 on 2019-03-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inStock',
            field=models.BooleanField(default=False),
        ),
    ]
