# Generated by Django 2.1.7 on 2019-03-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_book_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='nrOfDownloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
